### ISSUE TITLE
want to add an contribution of C program for Hacktoberfest 2021

### ISSUE THREAD

**Issue by AryamanGurjar** [GOVINDARAJLE/Hacktoberfest-2021#19]
Hello Sir,
 I want to Contribute to your repository for Hacktoberfest.
I want to contribute a BMI Calculator C program :-)

**Comment by Sourajita21** [comment]
I want to contribute on your repository sir. I will like to add the code of Minesweeper Game  and Tic-Tac-Toe game. Please assign this to me sir. Thank you sir thanks for your time.

**Comment by AryamanGurjar** [comment]
Hello sir can you please accept my pull request :-)
if it has some problem please let me know so that I can make the changes 😅
and sorry if I am disturbing you 
 
@GOVINDARAJLE
![12](https://user-images.githubusercontent.com/82881082/135747415-4b495d0e-e5da-4e74-92d5-be0f6cc01b18.PNG)
